version: '2'

services:
  web:
    image : yushi/rpi-motion
    privileged: true
    devices:
     - "/dev/video0:/dev/video0"
    ports:
     - "8081:8081"
     - "8080:8080"
    environment:
     - MOTION_DISABLE_MOVIE_OUTPUT=1
     - MOTION_DISABLE_IMAGE_OUTPUT=1
    volumes:
     - ./volumes/motion/config/motion.conf:/etc/motion/motion.conf
     - ./volumes/motion/data:/var/lib/motion
